from __future__ import annotations

from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from lattice.compiler.quality import filter_records
from lattice.compiler.transforms import build_views
from lattice.ingest import ingest_directory
from lattice.models import Record
from lattice.utils import ensure_dir, write_json, write_jsonl


@dataclass(slots=True)
class CompilerConfig:
    input_dir: str
    output_dir: str
    domain: str
    dataset_name: str
    chunk_size: int = 1200


def _schema_counts(records: list[Record]) -> dict[str, int]:
    counts: Counter[str] = Counter(record.schema_type for record in records)
    return dict(counts)


def _source_counts(records: list[Record]) -> dict[str, int]:
    counts: Counter[str] = Counter(record.metadata.source_type for record in records)
    return dict(counts)


def _dataset_card(manifest: dict[str, Any]) -> str:
    lines = [
        f"# Dataset Card: {manifest['dataset_name']}",
        "",
        f"- Domain: {manifest['domain']}",
        f"- Raw records: {manifest['raw_record_count']}",
        f"- Kept records: {manifest['kept_record_count']}",
        "",
        "## Schema Counts",
    ]
    for schema_name, count in manifest["schema_counts"].items():
        lines.append(f"- {schema_name}: {count}")
    lines.extend(["", "## View Counts"])
    for view_name, count in manifest["view_counts"].items():
        lines.append(f"- {view_name}: {count}")
    lines.extend(["", "## Dropped Records"])
    if manifest["dropped_records"]:
        for reason, count in manifest["dropped_records"].items():
            lines.append(f"- {reason}: {count}")
    else:
        lines.append("- none")
    lines.extend(["", "## Source Coverage"])
    for source_type, count in manifest["source_counts"].items():
        lines.append(f"- {source_type}: {count}")
    if manifest["warnings"]:
        lines.extend(["", "## Warnings"])
        for warning in manifest["warnings"]:
            lines.append(f"- {warning}")
    lines.extend(
        [
            "",
            "## Notes",
            "- This release is generated by the Lattice Phase 1 compiler.",
            "- Every exported view item keeps a source record id and provenance chain.",
        ]
    )
    return "\n".join(lines) + "\n"


def compile_dataset(config: CompilerConfig) -> dict[str, Any]:
    raw_records, warnings = ingest_directory(config.input_dir, config.domain)
    filtered_records, dropped = filter_records(raw_records)
    views = build_views(filtered_records, config.dataset_name, config.chunk_size)

    output_dir = ensure_dir(config.output_dir)
    normalized_dir = ensure_dir(output_dir / "normalized")
    views_dir = ensure_dir(output_dir / "views")
    reports_dir = ensure_dir(output_dir / "reports")

    write_jsonl(normalized_dir / "records.jsonl", [record.to_dict() for record in filtered_records])
    for view_name, rows in views.items():
        write_jsonl(views_dir / f"{view_name}.jsonl", rows)

    manifest = {
        "dataset_name": config.dataset_name,
        "domain": config.domain,
        "input_dir": str(Path(config.input_dir).resolve()),
        "output_dir": str(output_dir.resolve()),
        "config": asdict(config),
        "raw_record_count": len(raw_records),
        "kept_record_count": len(filtered_records),
        "dropped_records": dict(dropped),
        "schema_counts": _schema_counts(filtered_records),
        "source_counts": _source_counts(filtered_records),
        "view_counts": {name: len(rows) for name, rows in views.items()},
        "warnings": warnings,
    }
    write_json(reports_dir / "manifest.json", manifest)
    write_json(reports_dir / "source_coverage.json", manifest["source_counts"])
    (reports_dir / "dataset_card.md").write_text(_dataset_card(manifest), encoding="utf-8")
    return manifest
